# Generated by Django 2.1.1 on 2019-01-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
